In [25]:
from sklearn.datasets import load_iris, load_digits, load_breast_cancer

data = load_digits()
X,Y = load_digits(return_X_y=True)

#print('Feature names:',data.feature_names)
print('Target names:',data.target_names)

print('X',X)
print('Y',Y)

Target names: [0 1 2 3 4 5 6 7 8 9]
X [[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
Y [0 1 2 ... 8 9 8]


## Training and test set

In [26]:
from sklearn.model_selection import train_test_split

Xtrain, Xtest, ytrain, ytest = train_test_split(X, Y, test_size=0.30, random_state=42)

print('X',X.shape)
print('Y',len(Y))

print('Xtrain',Xtrain.shape)
print('ytrain',len(ytrain))
print('Xtest',Xtest.shape)
print('ytest',len(ytest))

X (1797, 64)
Y 1797
Xtrain (1257, 64)
ytrain 1257
Xtest (540, 64)
ytest 540


## Model

In [38]:
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB 
from sklearn.metrics import accuracy_score
import numpy as np

model = MLPClassifier(random_state=42)

# Ajustar (Entrenar) el modelo con los datos de entrenamiento
model.fit(Xtrain,ytrain)

# Predecir
ypred = model.predict(Xtest)
#print('ytest:',ytest)
#print('ypred:',ypred)
print('accuracy_score',accuracy_score(ytest,ypred))

print('Número de muestras:',len(ytest))
print('Número de predicciones correctas:', np.sum(ytest==ypred))

accuracy_score 0.9666666666666667
Número de muestras: 540
Número de predicciones correctas: 522


In [41]:
from sklearn.metrics import confusion_matrix
import pandas
m = confusion_matrix(ytest, ypred)

df = pandas.DataFrame(m,columns=data.target_names,index=data.target_names)
df

0   1   2   3   4   5   6   7   8   9
0  52   0   1   0   0   0   0   0   0   0
1   0  48   0   0   0   0   0   0   2   0
2   0   0  47   0   0   0   0   0   0   0
3   0   0   1  50   0   1   0   0   2   0
4   0   0   0   0  60   0   0   0   0   0
5   0   0   0   0   0  61   1   1   0   3
6   1   0   0   0   0   0  52   0   0   0
7   0   0   0   0   0   0   0  54   0   1
8   0   1   1   0   0   1   0   0  40   0
9   0   0   0   0   0   0   0   0   1  58